// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yodpwhkfjsowqhbkaxkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvZHB3aGtmanNvd3FoYmtheGt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjI1MTAsImV4cCI6MjA2NTUzODUxMH0.q_sc_7rt__hftnja2bng8O5eIT_oM0RLSEIbUZIVFKg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);